<a href="https://colab.research.google.com/github/jesusfiguera1520-star/Sectur_Checklist/blob/main/%5BEstatistica%5D2026_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Introdução ao Python**

## **Função Print**

In [ ]:
# A função print() é utilizada para imprimir informações
print("Bem-vindo á introdução ao Python")

Bem-vindo á introdução ao Python

##**Print, Variaveis e operações matematicas**

In [ ]:
Nome = "Jesus" # Variável do tipo 'string'
a = 18         # variável do tipo 'int'
b = 2,5        # variável tipo 'float'

print("A informação da variável é:", a)

A informação da variável é: 18

In [ ]:
# Definir as variáveis
disciplina = "Estatística"
qtd_alunos = 35
qtd_aprovados = 31

# Processamento: calcular a taxa de aprovação
# taxa aprovação = (alunos aprovados / total de alunos)*100

taxa = round((qtd_aprovados / qtd_alunos)*100, 5)

taxa_arredondada = round(taxa , 3)
# Imprimir o resultado
print("A taxa de aprovação é:", taxa, "%")
print(f"A taxa de aprovação da disciplina de {disciplina} é: {taxa}%")
print(qtd_alunos**(1/2))

print(taxa_arredondada)

A taxa de aprovação é: 88.57143 %
A taxa de aprovação da disciplina de Estatística é: 88.57143%
5.916079783099616
88.571

## Interagindo com o Python

In [ ]:
nome = input("Qual o seu nome")
N1 = float(input("Qual a sua nota na prova 1?"))
N2 = float(input('Qual a sua nota na prvoa 2?'))
N3 = float(input('Qual a sua nota na prova 3?'))

#Calcular a media aritmetica
Nf = int(N1 + N2 + N3)/3

# Imprimir o resultado
print('\n')
print(f"A média do aluno {nome} é: {Nf}")

Qual o seu nomeJesus
Qual a sua nota na prova 1?8
Qual a sua nota na prvoa 2?7
Qual a sua nota na prova 3?6


A média do aluno Jesus é: 7.0

In [ ]:
a = int(9.3)

print(type(a))
print(a)

<class 'int'>
9

## Listas

In [ ]:
# Dados: lista de notas
lista_notas = [N1 , N2 , N3, 8]

# Processamento: cálculo da média
media_lista = round(sum(lista_notas) / (len(lista_notas)),1)

#imprimir resultado
print(f"A média é: {media_lista}")

A média é: 7.2

In [ ]:
"""
Proble: Usuario informa nota 1, nota 2 e media de aprovação
e o algoritmo deve retornar a nota mínima necessária para aprovação
"""
# Coletar Dados
Not1 = float(input("Qual a sua nota na prova 1:"))
Not2 = float(input("Qual a sua nota na prova 2:"))
aprovacao = float(input("Qual a sua nota minima para aprovar:"))
#Processamento: calcular qual deve ser a N3 mínima

Not3 = round((aprovacao*3)-Not1-Not2,2)

#Imprimir o resultado
print(f"A nota que você precisa é: {Not3}")

Qual a sua nota na prova 1:5
Qual a sua nota na prova 2:6
Qual a sua nota minima para aprovar:6
A nota que você precisa é: 7.0

##Atividade 2

Problema 2
SITUAÇÃO: No mercado do Sr. João, o preço de
venda dos produtos comercializados são calculados
acrescentado 40% nos respectivos preços de custo
(lucro do Sr. João).
Crie um código para calcular o preço de custo de
um determinado produto que é vendido no
mercado do Sr. João.

In [ ]:
#Coleta das informações
venda = float(input("Valor do produto: "))
Lucro = venda * 2 / 7

#Processamento das informações
custo = venda - Lucro

#resultado
print("\n")
print(f"O valor de custo é: {custo}")

Valor do produto: 28


O valor de custo é: 20.0

##Dicionários e Dataframes

In [ ]:
dicionario = {
'Aluno1':[4.8, 9.8, 10.0],
'Aluno2':[8.4, 7.1, 4.6],
'Aluno3':[7.5, 6.0, 2.7]
}

print(dicionario)

{'Aluno1': [4.8, 9.8, 10.0], 'Aluno2': [8.4, 7.1, 4.6], 'Aluno3': [7.5, 6.0, 2.7]}

In [ ]:
# Importar a biblioteca Pandas
# Pandas é um repositorio onde estão disponiveís diversas função para manipulação de tabelas (dataframes)
import pandas as pd

#Converter o dicionário em uma estrutura de DataFrame
df = pd.DataFrame(dicionario)

#Visualizar o Dataframe
#print(df)
df.head()

   Aluno1  Aluno2  Aluno3
0     4.8     8.4     7.5
1     9.8     7.1     6.0
2    10.0     4.6     2.7

In [ ]:
# Inserir uma nova coluna com a média de cada prova

df['Media_Provas'] = round(
    (df['Aluno1'] + df['Aluno2'] + df['Aluno3']) / 3,
    1
 )
df.head()

   Aluno 1  Aluno 2  Aluno 3  Media_Provas
0      4.8      8.4      7.5           6.9
1      9.8      7.1      6.0           7.6
2     10.0      4.6      2.7           5.8

In [ ]:
# Importar a biblioteca Numpy (operações matemáticas)
import numpy as np

media_Aluno1 = round(np.mean(df['Aluno1']),1)
media_Aluno2 = round(np.mean(df['Aluno2']),1)
media_Aluno3 = round(np.mean(df['Aluno3']),1)

print(f'Média do Aluno 1: {media_Aluno1}')
print(f'Média do Aluno 2: {media_Aluno2}')
print(f'Média do Aluno 3: {media_Aluno3}')

Média do Aluno 1: 8.2
Média do Aluno 2: 6.7
Média do Aluno 3: 5.4

##Importar um arquivo Externo para o Colab

In [ ]:
import pandas as pd

df_bcd = pd.read_excel('/content/[Estatistica-BCD]_DadosQuestionario_20262.xlsx')

df_bcd.head(50)

,ID,Semestre,Cidade de origem,Estado de origem,Cidade em que você reside atualmente.,Você já morou em quantas cidades?,Você já teve contato com programação?,Qual linguagem você já utilizou?,Você gosta de Matemática?,Como você avalia seu conhecimento em Matemática?,...,Você trabalha atualmente?,Tempo diário médio de uso de redes sociais (em horas).,"Quantas vezes na semana, em média, você pratica atividade física?",Como você avalia seu cuidado com sua alimentação?,Quantos pets você tem?,Quantos livros você leu no último ano?,Quantos idiomas você sabe?,Você prefere:,Principal motivo para escolher Ciência de Dados:,Áreas que mais te interessam:
0,1,2026/1,Blumenau,SC,Blumenau,1,Avançado,"SQL, Python, R",Sim,10,...,"Sim, período integral",1 a 2,2,6,2,7,1,Ambos,Oportunidades profissionais;Interesse em inova...,Análise de Dados;Pesquisa;Inteligência Artific...
1,2,2026/1,Blumenau,Santa Catarina,Blumenau,0,Intermediário,Java,Sim,7,...,"Sim, período integral",1 a 2,1,4,0,1,1,Trabalhar em equipe,Interesse em tecnologia;Oportunidades profissi...,Inteligência Artificial;Tecnologia;Análise de ...
2,3,2026/2,Belo Horizonte,Minas Gerais,Blumenau,3,Básico,C#,Sim,6,...,"Sim, período integral",3 a 4,3,4,2,0,2,Ambos,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Tecno...
3,4,2026/1,Blumenau,Santa Catarina,Blumenau,0,Básico,Java script,Não,6,...,"Sim, período integral",3 a 4,2,5,2,0,1,Ambos,Interesse em inovação;Interesse em tecnologia;...,Análise de Dados;Inteligência Artificial;Negóc...
4,5,2026/1,Blumenau,Santa Catarina,Blumenau,1,Básico,"Java, SQL, CSS, Javascript",Sim,7,...,Não,5 a 6,2,2,2,8,2,Ambos,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Tecno...
5,6,2026/1,Blumenau,Santa Catarina,Blumenau,3,Básico,Python,Sim,10,...,"Sim, meio período",3 a 4,2,5,0,0,2,Ambos,Interesse em matemática/estatística;Interesse ...,Inteligência Artificial;Análise de Dados;Negóc...
6,7,2026/1,Joinville,Santa Catarina,Blumenau,2,Básico,C#,Sim,7,...,"Sim, período integral",1 a 2,2,5,1,2,1,Trabalhar em equipe,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Negóc...
7,8,2026/1,Blumenau,SC,Blumenau,1,Básico,"Java, Javascript",Sim,6,...,"Sim, período integral",1 a 2,0,7,2,3,2,Ambos,Interesse em tecnologia;Interesse em inovação;...,Inteligência Artificial;Análise de Dados;Tecno...
8,9,2026/1,Timbó,Santa Catarina,Timbó,0,Básico,"Python, SQL",Sim,7,...,"Sim, meio período",1 a 2,3,8,2,35,2,Ambos,Oportunidades profissionais;,Análise de Dados;
9,10,2026/1,Timbó,Santa Catarina,Rodeio,1,Básico,"Java, Python, JavaScript, SQL",Sim,8,...,"Sim, período integral",1 a 2,0,7,3,0,1,Ambos,Oportunidades profissionais;Interesse em tecno...,Análise de Dados;Pesquisa;Tecnologia;Negócios;...
10,11,2026/1,blumenau,sc,blumenau,1,Nunca,NaN,Sim,5,...,"Sim, período integral",1 a 2,3,7,0,23,2,Ambos,Interesse em inovação;Interesse em tecnologia;...,Análise de Dados;Inteligência Artificial;Ainda...
11,12,2026/1,Blumenau,Santa Catarina,Blumenau,1,Nunca,NaN,Sim,7,...,Não,3 a 4,2,5,mais que 10,0,2,Ambos,Oportunidades profissionais;Interesse em tecno...,Ainda não sei;
12,13,2026/1,Gaspar,SC,Gaspar,1,Básico,Java,Sim,6,...,"Sim, período integral",1 a 2,1,5,4,2,2,Ambos,Interesse em tecnologia;Oportunidades profissi...,Inteligência Artificial;Tecnologia;
13,14,2026/1,Gaspar,Santa Catarina,Gaspar,0,Básico,"python, java, java script, sql",Sim,7,...,"Sim, meio período",3 a 4,5,7,3,0,2,Ambos,Interesse em tecnologia;Interesse em inovação;...,Inteligência Artificial;Análise de Dados;Negóc...
14,15,2026/1,Curitibanos,Santa Catarina,Blumenau,2,Nunca,NaN,Sim,6,...,"Sim, período integral",1 a 2,4,4,0,1,1,Ambos,Outros;,Tecnologia;Pesquisa;Negócios;Análise de Dados;
15,16,2026/1,Timbó,SC,Timbó,0,Básico,"Java, SQL e python",Sim,7,...,"Sim, período integral",3 a 4,2,8,0,5,1,Ambos,Oportunidades profissionais;Interesse em tecno...,Análise de Dados;Tecnologia;
16,17,2026/1,Blumenau,SC,Blumenau,1,Intermediário,"Java,PHP",Sim,6,...,"Sim, período integral",3 a 4,5,8,2,3,1,Trabalhar individualmente,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Tecno...
17,18,2026/1,Belo Horizonte,Minas Gerais,Blumenau,3,Nunca,NaN,Sim,6,...,Não,1 a 2,0,8,4,1,1,Ambos,Interesse em tecnologia;Interesse em inovação;...,Tecnologia;Negócios;Análise de Dados;Inteligên...
18,19,2026/1,São Gonçalo,Rio de Janeiro,Blumenau,3,Básico,Java,Sim,5,...,"Sim, meio período",1 a 2,7,8,0,1,1,Ambos,Oportunidades profissionais;Interesse em inova...,Inteligência Artificial;Análise de Dados;Negóc...
19,20,2026/1,Londres,Estrangeiro,Blumenau,2,Básico,Python,Sim,7,...,Não,1 a 2,4,8,1,5,2,Ambos,Oportunidades profissionais;Interesse em tecno...,Análise de Dados;Tecnologia;Inteligência Artif...
20,21,2026/1,Otacílio Costa,Sc,Blumenau,3,Básico,"C#, flutter, Dart, C, C++",Sim,6,...,"Sim, período integral",1 a 2,4,5,0,5,2,Trabalhar individualmente,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Tecno...
21,22,2026/1,Blumenau,SC,Blumenau,0,Intermediário,"Java, Flutter, SQL, Python",Não,7,...,Não,1 a 2,5,10,5,3,3,Trabalhar em equipe,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Negóc...
22,23,2026/1,Blumenau,Santa catarina,blumenau,2,Básico,Phyton,Sim,7,...,"Sim, meio período",1 a 2,mais que 7,8,1,5,3,Trabalhar em equipe,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Negóc...
23,24,2026/1,Blumenau,SC,Blumenau,2,Básico,"Python, Rust",Sim,5,...,"Sim, período integral",1 a 2,2,8,0,2,3,Ambos,Transição de carreira;Oportunidades profission...,Inteligência Artificial;Análise de Dados;
24,25,2026/1,Blumenau,Santa Catarina,Blumenau,1,Nunca,NaN,Sim,9,...,Não,1 a 2,4,10,1,12,2,Trabalhar em equipe,Oportunidades profissionais;Interesse em tecno...,Negócios;Tecnologia;Inteligência Artificial;
25,26,2026/1,Teresópolis,RJ,Blumenau,2,Intermediário,"C, Java, Python, SQL",Sim,7,...,"Sim, período integral",1 a 2,2,7,1,4,1,Trabalhar individualmente,Interesse em matemática/estatística;Interesse ...,Análise de Dados;Pesquisa;Tecnologia;
26,27,2026/1,Chapecó,Santa Catarina,Blumenau,3,Básico,Vibe coding,Não,3,...,"Sim, período integral",mais de 6,5,8,2,0,3,Ambos,Outros;,Inteligência Artificial;Negócios;Tecnologia;
27,28,2026/1,Blumenau,Santa Catarina,Blumenau,1,Nunca,NaN,Sim,8,...,"Sim, período integral",mais de 6,mais que 7,8,1,1,1,Ambos,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Tecno...
28,29,2026/1,blumenau,SC,blumenau,1,Nunca,NaN,Sim,7,...,Não,1 a 2,4,5,mais que 10,2,1,Trabalhar em equipe,Interesse em tecnologia;Oportunidades profissi...,Inteligência Artificial;Pesquisa;Tecnologia;Ne...
29,30,2026/1,Blumenau,Santa Catarina,Blumenau,0,Básico,Python,Sim,6,...,"Sim, período integral",mais de 6,3,7,3,2,2,Ambos,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;
30,31,2026/1,Blumenau,Santa Cararina,Blumenau,1,Avançado,"Java, JavaScript, JSP em geral, HTML/CSS, Flut...",Não,3,...,"Sim, meio período",1 a 2,2,4,5,2,2,Ambos,Outros;Oportunidades profissionais;Interesse e...,Inteligência Artificial;Análise de Dados;Tecno...
31,32,2026/1,Caraguatatuba,São Paulo,Blumenau,3,Intermediário,"Phyton, C, Java, Assembly",Sim,6,...,Não,1 a 2,3,6,3,4,2,Ambos,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Pesqu...
32,33,2026/1,Blumenau,SC,Blumenau,1,Nunca,NaN,Não,8,...,Não,3 a 4,5,9,0,5,3,Trabalhar em equipe,Interesse em tecnologia;Interesse em inovação;,Inteligência Artificial;Análise de Dados;Negóc...
33,34,2026/1,BLUMENAU,SC,BLUMENAU,1,Nunca,NaN,Sim,5,...,"Sim, período integral",1 a 2,3,7,0,23,2,Ambos,Interesse em inovação;Interesse em tecnologia;...,Inteligência Artificial;Análise de Dados;Tecno...
34,35,2026/1,Rodeio,Santa Catarina,Rodeio,1,Intermediário,"Python, HTML, JavaScript, CSS, SQL",Sim,8,...,Não,3 a 4,5,6,1,5,2,Ambos,Oportunidades profissionais;Outros;Interesse e...,Inteligência Artificial;Análise de Dados;Negóc...
35,36,2026/1,Ilhota,Santa Catarina,Ilhota,6,Nunca,NaN,Sim,7,...,"Sim, período integral",1 a 2,5,8,1,0,1,Trabalhar em equipe,Interesse em tecnologia;Interesse em inovação;...,Inteligência Artificial;Análise de Dados;Negóc...
36,37,2026/1,Blumenau,Santa Catarina,Blumenau,5,Nunca,NaN,Sim,7,...,"Sim, período integral",3 a 4,3,8,2,9,3,Trabalhar individualmente,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;
37,38,2026/1,Santa Maria,RS,Blumenau,3,Básico,Python,Sim,6,...,Não,1 a 2,1,3,2,2,2,Trabalhar individualmente,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Negóc...
38,39,2026/1,São Paulo,SP,Timbó,2,Intermediário,"Python, SQL",Sim,8,...,"Sim, período integral",1 a 2,0,8,4,7,2,Ambos,Oportunidades profissionais;,Análise de Dados;Inteligência Artificial;
39,40,2026/1,Gaspar,Santa Catarina,Gaspar,1,Básico,Python,Sim,7,...,"Sim, período integral",3 a 4,1,5,1,1,1,Trabalhar em equipe,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Tecnologia;Análise de ...
40,41,2026/1,Indaial,Sc,Rodeio,0,Básico,Javascript,Sim,5,...,"Sim, período integral",3 a 4,0,5,0,0,0,Ambos,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Tecno...
41,42,2026/1,Ilhota,Sc,Ilhota,1,Intermediário,Java,Sim,7,...,"Sim, período integral",3 a 4,1,3,2,1,3,Ambos,Oportunidades profissionais;Interesse em tecno...,Inteligência Artificial;Análise de Dados;Tecno...
42,43,2026/1,Blumenau,SC,Blumenau,1,Intermediário,Java,Não,7,...,"Sim, período integral",3 a 4,5,7,2,1,1,Ambos,Oportunidades profissionais;Interesse em tecno...,Análise de Dados;Inteligência Artificial;Tecno...
43,44,2026/1,Recife,Pernambuco,Blumenau,2,Básico,Programação em c,Não,7,...,"Sim, período integral",3 a 4,4,7,4,1,1,Ambos,Interesse em tecnologia;Oportunidades profissi...,Inteligência Artificial;Tecnologia;Análise de ...
44,45,2026/1,Belém,Para,Blumenau,2,Básico,C#,Não,8,...,"Sim, período integral",1 a 2,4,7,1,0,2,Trabalhar em equipe,Oportunidades profissionais;Interesse em tecno...,Análise de Dados;Tecnologia;
45,46,2026/1,Foz do Iguaçu,Paraná,Blumenau,1,Intermediário,"Java script, Java, Python, C#, Delphi",Não,6,...,"Sim, período integral",3 a 4,2,8,3,2,2,Ambos,Transição de carreira;Oportunidades profission...,Inteligência Artificial;Análise de Dados;Negóc...
46,47,2026/1,Blumenau,SC,Blumenau,1,Intermediário,"Java, SQL, HTML, CSS, JS",Sim,5,...,"Sim, meio período",3 a 4,4,6,1,4,2,Ambos,Interesse em tecnologia;Interesse em inovação;,Inteligência Artificial;Análise de Dados;Tecno...
47,48,2026/1,Pomerode,Santa Catarina,Pomerode,0,Nunca,NaN,Sim,8,...,Não,5 a 6,4,2,1,0,2,Ambos,Oportunidades profissionais;Interesse em tecno...,Tecnologia;Inteligência Artificial;Análise de ...
48,49,2026/1,Blumenau,SC,Blumenau,1,Intermediário,Java,Sim,8,...,Não,1 a 2,0,10,2,0,1,Ambos,Interesse em tecnologia;Outros;,Inteligência Artificial;Análise de Dados;
49,50,2026/1,Recife,Pernambuco,Blumenau,2,Intermediário,"ABAP, SQL",Sim,8,...,"Sim, período integral",3 a 4,1,5,1,1,2,Trabalhar individualmente,Oportunidades profissionais;Interesse em tecno...,Análise de Dados;Tecnologia;

In [ ]:
df_bcd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 22 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0   ID                                                                                80 non-null     int64
 1   Semestre                                                                          80 non-null     object
 2   Cidade de origem                                                                  80 non-null     object
 3   Estado de origem                                                                  80 non-null     object
 4   Cidade em que você reside atualmente.                                             80 non-null     object
 5   Você já morou em quantas cidades?                                                 80 non-null     int64
 6   Você já teve contato com programação?                                             80 non-null     object
 7   Qual linguagem você já utilizou?                                                  58 non-null     object
 8   Você gosta de Matemática?                                                         80 non-null     object
 9   Como você avalia seu conhecimento em Matemática?                                  80 non-null     int64
 10  Data de nascimento:                                                               80 non-null     datetime64[ns]
 11  Quantas horas (extra sala de aula) por semana você pretende se dedicar ao curso?  80 non-null     object
 12  Você trabalha atualmente?                                                         80 non-null     object
 13  Tempo diário médio de uso de redes sociais (em horas).                            80 non-null     object
 14  Quantas vezes na semana, em média, você pratica atividade física?                 80 non-null     object
 15  Como você avalia seu cuidado com sua alimentação?                                 80 non-null     int64
 16  Quantos pets você tem?                                                            80 non-null     object
 17  Quantos livros você leu no último ano?                                            80 non-null     int64
 18  Quantos idiomas você sabe?                                                        80 non-null     int64
 19  Você prefere:                                                                     80 non-null     object
 20  Principal motivo para escolher Ciência de Dados:                                  80 non-null     object
 21  Áreas que mais te interessam:                                                     80 non-null     object
dtypes: datetime64[ns](1), int64(6), object(15)
memory usage: 13.9+ KB

In [ ]:
df_bcd.describe()

,ID,Você já morou em quantas cidades?,Como você avalia seu conhecimento em Matemática?,Data de nascimento:,Como você avalia seu cuidado com sua alimentação?,Quantos livros você leu no último ano?,Quantos idiomas você sabe?
count,80.0000,80.000000,80.000000,80,80.000000,80.000000,80.000000
mean,40.5000,1.725000,6.662500,2004-08-13 08:06:00,6.225000,3.462500,1.987500
min,1.0000,0.000000,2.000000,1975-03-18 00:00:00,0.000000,0.000000,0.000000
25%,20.7500,1.000000,6.000000,2003-02-24 18:00:00,5.000000,1.000000,1.000000
50%,40.5000,1.000000,7.000000,2006-07-02 12:00:00,6.500000,2.000000,2.000000
75%,60.2500,2.000000,8.000000,2007-12-01 06:00:00,8.000000,4.000000,2.000000
max,80.0000,9.000000,10.000000,2026-12-16 00:00:00,10.000000,35.000000,15.000000
std,23.2379,1.475324,1.492121,NaN,2.210304,5.641043,1.641964

#M**edidas de Posição**

In [22]:
import pandas as pd
import numpy as np
from scipy.stats import trim_mean

In [21]:
df = pd.read_excel('/content/[Estatistica-BCD]_DadosQuestionario_20262_(2).xlsx', sheet_name="DadosTratadosV2")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 35 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                80 non-null     int64
 1   SEMESTRE          80 non-null     object
 2   C_ORIGEM          80 non-null     object
 3   E_ORIGEM          80 non-null     object
 4   C_RESIDE          80 non-null     object
 5   QTD_MORADIAS      80 non-null     int64
 6   EX_PROGRAMACAO    80 non-null     object
 7   EX_PYTHON         80 non-null     int64
 8   EX_R              80 non-null     int64
 9   EX_JAVA           80 non-null     int64
 10  EX_SQL            80 non-null     int64
 11  MATEMATICA        80 non-null     object
 12  CONHECIMENTO_MAT  80 non-null     int64
 13  IDADE             79 non-null     float64
 14  ESTUDO_EC         80 non-null     object
 15  TRABALHA          80 non-null     object
 16  REDES SOCIAIS     80 non-null     object
 17  ATV_FISICA        80 non-null     object
 18  ALIMENTACAO       80 non-null     int64
 19  PETS              80 non-null     object
 20  LIVROS            80 non-null     int64
 21  IDIOMAS           80 non-null     int64
 22  MOD_TRABALHO      80 non-null     object
 23  INTERESE_OP       80 non-null     int64
 24  INTERESSE_TEC     80 non-null     int64
 25  INTERESSE_INO     80 non-null     int64
 26  INTERESSE_EST     80 non-null     int64
 27  INTERESSE_CAR     80 non-null     int64
 28  INTERESSE_OUTROS  80 non-null     int64
 29  AREA_IA           80 non-null     int64
 30  AREA_AD           80 non-null     int64
 31  AREA_NEG          80 non-null     int64
 32  AREA_PESQ         80 non-null     int64
 33  AREA_TEC          80 non-null     int64
 34  AREA_NAO_SABE     80 non-null     int64
dtypes: float64(1), int64(22), object(12)
memory usage: 22.0+ KB

In [37]:
# Selecionar as variaveis que serão utilizadas
idade       = df['IDADE']             #Melhor medida é a Mediana
cidade      = df['C_RESIDE']          #Melhor medida é a Moda
LIVROS      = df['LIVROS']            #Melhor medida é a Mediana
PROGRAMACAO = df['EX_PROGRAMACAO']    #Melhor medida é a Moda

In [41]:
#MEDIDAS DE POSIÇAO

## Média aritmética simples
media_simples1 = idade.mean() # com função nativa do python
media_simples2 = np.mean(idade) # com numpy (np)
# ':.2f' serve para fazer arredondação

print(f'A média simples 1 da idade é: {media_simples1:.1f}')

media_livros = np.mean(LIVROS)
print(f'A média livros: {media_livros:.1f}')

## Média ponderada
dados = [7.5, 8.2, 4.6, 6.0]
pesos = [0.20, 0.30, 0.35, 0.15]
pesos2 = [1, 3, 4, 2]

media_ponderada = np.average(dados, weights=pesos)
media_ponderada2 = np.average(dados, weights=pesos2)

print(f'A média ponderada é: {media_ponderada:.2f}')
print(f'A média ponderada2 é: {media_ponderada2:.2f}')

## Média aparada
media_aparada = trim_mean(idade, 0.1)
print(f'A média aparada: {media_aparada:.1f}')

## Mediana
mediana1 = idade.median()     # Com função nativa do Python
mediana2 = np.nanmedian(idade)   # Com função de numpy  # 'nan' para não tomar em conta os valores vazios (nan)

print(f'A mediana1: {mediana1:.1f}')
print(f'A mediana2: {mediana2:.1f}')

mediana_livros = np.median(LIVROS)
print(f'A mediana livros: {mediana_livros:.1f}')

## Moda
import statistics as st
moda1 = cidade.mode()
moda2 = st.mode(cidade)
# moda1 = cidade.mode() função do python, so imprime como tabela
print(f'Moda: {moda2}')

moda_prog = st.mode(PROGRAMACAO)
print(f'Moda Programaçãa: {moda_prog}')

A média simples 1 da idade é: 21.9
A média livros: 3.5
A média ponderada é: 6.47
A média ponderada2 é: 6.25
A média aparada: 20.7
A mediana1: 20.0
A mediana2: 20.0
A mediana livros: 2.0
Moda: Blumenau
Moda Programaçãa: Básico